### PR TITLE
Initial draft for feedback

### PR DESCRIPTION
**Pull request by ronguest**
Didn’t want to go to far with this for brevity sake as well as needing feedback. Directionally I thought of a few approaches. One as drafted; another would have been more scenario/use-case/persona based. This topic was one that tripped me up a lot at first and still gives me pause. Edits welcomed of course and complete rejection of this request is fine too. It won’t hurt my feelings. Cheers.

### CODE REVIEW

**Comment by sardisson** [comment]
@ronguest I just did a quick read-through on this; there are a bunch of style/grammar changes I'd make (commas, capitalizations, “tap” instead of “click”, etc.), but the content pretty much matches what I’d have in mind for this topic (I don’t think there’s an article for the web stuff for hosted blogs yet, and that seems like something to add in another article—and link to/from here—at some point).

One missing thing I do think you should add, just briefly: in the iOS app, in the default (square) configuration, you can also pan/drag (l/r or u/d, depending on the photo’s original orientation) to change where the square is cropped, and you can also unpinch (is that what the gesture is called?) to zoom in.

I’m not going to have any time this week to do a detailed rundown/fix of the style/grammar stuff, but I’ll try to give it (or a later draft) a thorough pass next week. Nice work, Ron.

**Comment by sardisson** [comment]
@ronguest Oh, one other thing; it might be useful to have a screenshot of the various screens so that people can see what you’re talking about as you’re talking about it. Screenshots are not very common in the M.b Help, but the [Wavelength guide](https://help.micro.blog/2018/wavelength/) has them, and it’s a similar type of article.

**Comment by ronguest** [comment]
Yeah I’m “experienced” and sometimes still use click! I never use the apps it on iPhone for viewing and even rarely for posting so I was hoping someone could help out on any experience differences vs the iPad. I definitely agree some images would be very helpful but hadn’t noticed them being used here so didn’t include them. It’s easy to add once the content is closer to agreed.

**Comment by manton** [comment]
@ronguest Thank you for starting this! I've only just skimmed it but I'll read through it again more closely tomorrow and provide feedback or minor edits. Looks like you have some good info captured here that isn't documented anywhere else.

@sardisson Good point. I think screenshots especially help when there are icons or other non-obvious parts of a UI that need clicking on.

**Comment by manton** [comment]
I think I'll merge this in today and then make a few other edits. Thanks!

**Pull request merged**
